name: build

on:
  push:
    branches:
      - rewrite
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: install jinja2-cli
        run: |
          python -m pip install --upgrade pip
          pip install jinja2-cli

      - name: build
        run: |
          xmake

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
